### ISSUE TITLE
Misplaced package names in graph view

### ISSUE THREAD

**Issue by Nautigsam** [Nohmapp/npm-introspect#6]
It seems that package names are shifted when I look at the graphics at http://localhost:8080, which makes it quite unreadable:

![spectacle qb4475](https://user-images.githubusercontent.com/7353930/27950861-2a7a8216-6303-11e7-9c93-05ee4453826f.png)

I reproduce in Firefox and Chromium.

**Comment by Nohmapp** [comment]
Did you have any additional package names in the cmd line or any more information about the input. Sometimes if the screen size changes after render it can truncate the svg but I've never seen anything like this.

**Comment by Nohmapp** [comment]
@Nautigsam What happens when you run the tool in a directory that wont contain cookie?

 I've been running the tool with a bunch of arguments and everytime I include the package cookie with enough packages to require a scroll bar I get this weird result where the cookie bar group will be labeled by another pkg, that label that is instead pointing to cookie its bar group will not be rendered and all the labels shift inward. Really confusing but if you could run the tool on some other packages and tell me what you get that'd be great.

**Comment by Nautigsam** [comment]
I'll test it today.

**Comment by Nohmapp** [comment]
The bar charts at the bottom were redesigned, see commit b78c2b967e98e086353523e3e9636b183a8294a6 . Or checkout the current version at http://npm-introspect.z3d.tech/
